# ------------------- Dashboard Service Account ------------------- #

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: eks-sso
  name: eks-sso
  namespace: kube-system

---
# ------------------- Dashboard Role & Role Binding ------------------- #

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-sso-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: eks-sso
  namespace: kube-system

---
# ------------------- EKS-SSO Deployment ------------------- #

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-sso
  name: eks-sso
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-sso
  template:
    metadata:
      labels:
        app: eks-sso
    spec:
      containers:
      - name: eks-sso
        image: quintilesims/eks-sso:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: EKS_SSO_CLUSTER_REGION
          value: "us-west-2"
        - name: EKS_SSO_CLUSTER_NAME
          value: "seshi"
        - name: EKS_SSO_AUTH0_CONNECTION
          value: "xfra-test-bind-4"
        - name: EKS_SSO_AUTH0_CLIENT_ID
          value: "g1EIAi6ygfpfnmBm27zj85696CwiKLys"
        - name: EKS_SSO_DEBUG
          value: "true"
        - name: EKS_SSO_IN_CLUSTER
          value: "true"
        - name: EKS_SSO_PORT
          value: "8080"
      serviceAccountName: eks-sso
---
# ------------------- EKS-SSO Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    app: eks-sso
  name: eks-sso
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: eks-sso